import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { aiApi, chatApi, patientApi } from '../api'

const QUICK_CONCERNS = [
  'I have chest pain and shortness of breath',
  'I have been having severe headaches',
  'I feel very tired and have lost weight',
  'I have stomach pain and nausea',
  'I have joint pain and swelling',
  'I have been feeling anxious and cannot sleep',
]

function CheckItem({ text, color = '#2a7c89' }) {
  const [checked, setChecked] = useState(false)
  return (
    <div
      className={`cp-check-item ${checked ? 'cp-checked' : ''}`}
      onClick={() => setChecked(v => !v)}
      style={{ borderLeftColor: checked ? color : 'transparent' }}
    >
      <div className="cp-checkbox" style={{ borderColor: color, background: checked ? color : 'transparent' }}>
        {checked && <span style={{ color: '#fff', fontSize: '0.7rem', fontWeight: 700 }}>✓</span>}
      </div>
      <p style={{ margin: 0, fontSize: '0.9rem', textDecoration: checked ? 'line-through' : 'none', color: checked ? '#94a3b8' : '#10243a', lineHeight: 1.5 }}>
        {text}
      </p>
    </div>
  )
}

function Section({ icon, title, color = '#2a7c89', children, defaultOpen = true }) {
  const [open, setOpen] = useState(defaultOpen)
  return (
    <div className="cp-section">
      <div className="cp-section-header" onClick={() => setOpen(v => !v)}>
        <div className="cp-section-icon" style={{ background: color + '14', color }}>{icon}</div>
        <h3 style={{ margin: 0, flex: 1, fontSize: '1rem' }}>{title}</h3>
        <span style={{ color: '#94a3b8', fontSize: '0.8rem' }}>{open ? '▲' : '▼'}</span>
      </div>
      {open && <div className="cp-section-body">{children}</div>}
    </div>
  )
}

export default function ConsultationPrep() {
  const navigate = useNavigate()
  const printRef = useRef(null)
  const [text, setText] = useState('')
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)
  const [profile, setProfile] = useState(null)
  const [activeTab, setActiveTab] = useState('questions')
  const [notes, setNotes] = useState('')

  useEffect(() => {
    patientApi.profile().then(({ data }) => setProfile(data)).catch(() => {})
    chatApi.history().then(({ data }) => {
      if (data[0]?.user_message) setText(data[0].user_message)
    }).catch(() => {})
  }, [])

  const run = async (q) => {
    const query = (q || text).trim()
    if (!query) return
    setText(query)
    setLoading(true)
    setResult(null)
    setActiveTab('questions')
    try {
      const { data } = await aiApi.consultationPrep(query, profile)
      setResult(data)
    } finally {
      setLoading(false)
    }
  }

  const handlePrint = () => {
    const content = printRef.current?.innerHTML
    if (!content) return
    const win = window.open('', '_blank')
    win.document.write(`
      <html><head><title>Consultation Prep Guide — HealthPilot</title>
      <style>
        body { font-family: 'Segoe UI', sans-serif; padding: 32px; color: #10243a; max-width: 700px; margin: 0 auto; }
        h1 { color: #14334a; border-bottom: 2px solid #2a7c89; padding-bottom: 10px; }
        h3 { color: #2a7c89; margin: 20px 0 8px; }
        .q { padding: 8px 12px; margin: 6px 0; background: #f0f9ff; border-left: 3px solid #2a7c89; border-radius: 4px; }
        .item { padding: 6px 0; border-bottom: 1px solid #e5e7eb; }
        .warn { background: #fef2f2; border-left: 3px solid #ef4444; padding: 8px 12px; margin: 6px 0; border-radius: 4px; color: #b91c1c; }
        .tag { display: inline-block; padding: 3px 10px; background: #e0f2fe; color: #0369a1; border-radius: 999px; margin: 3px; font-size: 0.85rem; }
        .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e5e7eb; font-size: 0.75rem; color: #94a3b8; }
      </style></head><body>
      <h1>🩺 Consultation Prep Guide</h1>
      <p><strong>Concern:</strong> ${text}</p>
      <p><strong>Generated:</strong> ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
      ${content}
      <div class="footer">Generated by HealthPilot AI · For personal use only · Not a substitute for medical advice</div>
      </body></html>
    `)
    win.document.close()
    win.print()
  }

  const guide = result?.consultation_guide
  const TABS = [
    { id: 'questions', label: '❓ Questions' },
    { id: 'checklist', label: '✅ Checklist' },
    { id: 'notes', label: '📝 My Notes' },
    { id: 'tips', label: '💡 Tips' },
  ]

  return (
    <div className="page-stack">
      {/* Hero */}
      <section className="cp-hero">
        <div>
          <p className="eyebrow" style={{ color: 'rgba(255,255,255,0.7)' }}>Consultation Prep</p>
          <h2 style={{ color: '#fff', margin: '6px 0 8px' }}>🩺 Prepare for Your Doctor Visit</h2>
          <p style={{ color: 'rgba(255,255,255,0.75)', margin: 0, fontSize: '0.9rem' }}>
            Get a personalised list of questions to ask your doctor, what to bring, and how to make the most of your appointment.
          </p>
        </div>
      </section>

      {/* Input */}
      <div className="glass-card cp-input-card">
        <p className="eyebrow">Describe your concern</p>
        <div style={{ display: 'flex', gap: 10 }}>
          <textarea rows={2} value={text} onChange={e => setText(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && !e.shiftKey && (e.preventDefault(), run())}
            placeholder="Describe your symptoms or health concern to generate a personalised prep guide…"
            style={{ flex: 1, resize: 'none' }} />
          <button className="primary-button" onClick={() => run()} disabled={loading || !text.trim()}
            style={{ alignSelf: 'flex-end', padding: '12px 22px', whiteSpace: 'nowrap' }}>
            {loading ? '⟳ Generating…' : '🩺 Generate Guide'}
          </button>
        </div>
        <div className="cp-quick-chips">
          {QUICK_CONCERNS.map(c => (
            <button key={c} className="cp-quick-chip" onClick={() => run(c)}>{c}</button>
          ))}
        </div>
      </div>

      {loading && (
        <div className="glass-card" style={{ padding: 40, textAlign: 'center' }}>
          <p style={{ fontSize: '1.5rem', marginBottom: 10 }}>⟳</p>
          <p style={{ fontWeight: 600 }}>Generating your personalised prep guide…</p>
          <p className="muted" style={{ fontSize: '0.85rem' }}>Analysing symptoms · Generating questions · Building checklist</p>
        </div>
      )}

      {result && (
        <>
          {/* Summary bar */}
          <div className="cp-summary-bar">
            <div className="cp-summary-item">
              <span className="cp-summary-icon" style={{ background: 'rgba(42,124,137,0.12)', color: '#2a7c89' }}>❓</span>
              <div>
                <p className="cp-summary-val">{(guide?.symptom_specific_questions?.length || 0) + (guide?.general_questions?.length || 0)}</p>
                <p className="cp-summary-label">Questions ready</p>
              </div>
            </div>
            <div className="cp-summary-item">
              <span className="cp-summary-icon" style={{ background: 'rgba(34,197,94,0.12)', color: '#22c55e' }}>🎒</span>
              <div>
                <p className="cp-summary-val">{guide?.what_to_bring?.length || 0}</p>
                <p className="cp-summary-label">Items to bring</p>
              </div>
            </div>
            <div className="cp-summary-item">
              <span className="cp-summary-icon" style={{ background: 'rgba(232,93,63,0.12)', color: '#e85d3f' }}>🏥</span>
              <div>
                <p className="cp-summary-val">{result.suggested_specialists?.length || 0}</p>
                <p className="cp-summary-label">Specialists suggested</p>
              </div>
            </div>
            <div className="cp-summary-item">
              <span className="cp-summary-icon" style={{ background: 'rgba(239,68,68,0.12)', color: '#ef4444' }}>🚩</span>
              <div>
                <p className="cp-summary-val">{guide?.red_flags_to_mention?.length || 0}</p>
                <p className="cp-summary-label">Red flags</p>
              </div>
            </div>
            <button className="ghost-button cp-print-btn" onClick={handlePrint}>
              🖨️ Print Guide
            </button>
          </div>

          {/* Tabs */}
          <div className="tab-bar">
            {TABS.map(t => (
              <button key={t.id} className={`tab-btn ${activeTab === t.id ? 'tab-btn-active' : ''}`}
                onClick={() => setActiveTab(t.id)}>{t.label}</button>
            ))}
          </div>

          {/* Printable content */}
          <div ref={printRef} style={{ display: 'none' }}>
            <h3>Symptom-Specific Questions</h3>
            {guide?.symptom_specific_questions?.map((q, i) => <div key={i} className="q">{q}</div>)}
            <h3>General Questions</h3>
            {guide?.general_questions?.map((q, i) => <div key={i} className="q">{q}</div>)}
            <h3>What to Bring</h3>
            {guide?.what_to_bring?.map((item, i) => <div key={i} className="item">✓ {item}</div>)}
            <h3>What to Tell Your Doctor</h3>
            {guide?.what_to_tell_doctor?.map((item, i) => <div key={i} className="item">• {item}</div>)}
            {guide?.red_flags_to_mention?.length > 0 && <>
              <h3>🚨 Red Flags to Mention</h3>
              {guide.red_flags_to_mention.map((f, i) => <div key={i} className="warn">⚠ {f}</div>)}
            </>}
            <h3>Suggested Specialists</h3>
            {result.suggested_specialists?.map((s, i) => <span key={i} className="tag">{s}</span>)}
            {notes && <><h3>My Notes</h3><p>{notes}</p></>}
          </div>

          {/* Questions tab */}
          {activeTab === 'questions' && (
            <div className="cp-sections">
              {guide?.red_flags_to_mention?.length > 0 && (
                <Section icon="🚨" title="Mention These Immediately" color="#ef4444">
                  <p className="muted" style={{ fontSize: '0.82rem', margin: '0 0 10px' }}>
                    Tell your doctor about these symptoms right away — do not wait until the end of the appointment.
                  </p>
                  {guide.red_flags_to_mention.map((f, i) => (
                    <div key={i} className="cp-redflag-item">
                      <span>⚠️</span>
                      <p style={{ margin: 0, fontWeight: 600, color: '#b91c1c', fontSize: '0.9rem' }}>{f}</p>
                    </div>
                  ))}
                </Section>
              )}

              <Section icon="🩺" title="Questions About Your Symptoms" color="#2a7c89">
                <p className="muted" style={{ fontSize: '0.82rem', margin: '0 0 12px' }}>
                  These questions are tailored to your specific symptoms. Ask them to understand your condition better.
                </p>
                {guide?.symptom_specific_questions?.map((q, i) => (
                  <div key={i} className="cp-question-card">
                    <span className="cp-q-num" style={{ background: '#2a7c89' }}>{i + 1}</span>
                    <p style={{ margin: 0, fontSize: '0.9rem', lineHeight: 1.6 }}>{q}</p>
                  </div>
                ))}
              </Section>

              <Section icon="📋" title="General Questions to Ask" color="#14334a">
                <p className="muted" style={{ fontSize: '0.82rem', margin: '0 0 12px' }}>
                  Ask these at every appointment to make sure you leave with a clear plan.
                </p>
                {guide?.general_questions?.map((q, i) => (
                  <div key={i} className="cp-question-card" style={{ borderLeftColor: '#14334a' }}>
                    <span className="cp-q-num" style={{ background: '#14334a' }}>{i + 1}</span>
                    <p style={{ margin: 0, fontSize: '0.9rem', lineHeight: 1.6 }}>{q}</p>
                  </div>
                ))}
              </Section>

              {result.suggested_specialists?.length > 0 && (
                <Section icon="🏥" title="Suggested Specialists" color="#e85d3f">
                  <p className="muted" style={{ fontSize: '0.82rem', margin: '0 0 10px' }}>
                    Based on your symptoms, you may benefit from seeing one of these specialists.
                  </p>
                  <div className="tag-row">
                    {result.suggested_specialists.map(s => (
                      <button key={s} className="tag tag-blue cp-specialist-tag"
                        onClick={() => navigate('/doctors')}>{s} →</button>
                    ))}
                  </div>
                  <p className="muted" style={{ fontSize: '0.75rem', marginTop: 8 }}>
                    Tap a specialist to find one near you.
                  </p>
                </Section>
              )}
            </div>
          )}

          {/* Checklist tab */}
          {activeTab === 'checklist' && (
            <div className="cp-sections">
              <Section icon="🎒" title="What to Bring" color="#22c55e">
                <p className="muted" style={{ fontSize: '0.82rem', margin: '0 0 12px' }}>
                  Tick each item as you pack it. Tap to mark as done.
                </p>
                {guide?.what_to_bring?.map((item, i) => (
                  <CheckItem key={i} text={item} color="#22c55e" />
                ))}
              </Section>

              <Section icon="💬" title="What to Tell Your Doctor" color="#2a7c89">
                <p className="muted" style={{ fontSize: '0.82rem', margin: '0 0 12px' }}>
                  Make sure you cover all of these points during your appointment.
                </p>
                {guide?.what_to_tell_doctor?.map((item, i) => (
                  <CheckItem key={i} text={item} color="#2a7c89" />
                ))}
              </Section>

              <Section icon="❓" title="Questions Checklist" color="#8b5cf6">
                <p className="muted" style={{ fontSize: '0.82rem', margin: '0 0 12px' }}>
                  Tick each question after you've asked it during your appointment.
                </p>
                {[...(guide?.symptom_specific_questions || []), ...(guide?.general_questions || [])].map((q, i) => (
                  <CheckItem key={i} text={q} color="#8b5cf6" />
                ))}
              </Section>
            </div>
          )}

          {/* Notes tab */}
          {activeTab === 'notes' && (
            <div className="glass-card cp-notes-card">
              <p className="eyebrow">📝 My Appointment Notes</p>
              <h3>Write down what your doctor says</h3>
              <p className="muted" style={{ fontSize: '0.85rem', margin: '0 0 14px' }}>
                Use this space to note down your doctor's answers, diagnosis, and next steps during or after your appointment.
              </p>
              <textarea
                value={notes}
                onChange={e => setNotes(e.target.value)}
                rows={12}
                placeholder="e.g. Doctor said my blood pressure is slightly elevated. Recommended reducing salt intake and returning in 4 weeks for a follow-up. Prescribed Amlodipine 5mg once daily…"
                style={{ width: '100%', resize: 'vertical' }}
              />
              <div style={{ display: 'flex', gap: 10, marginTop: 10 }}>
                <button className="ghost-button" onClick={handlePrint} disabled={!notes.trim()}>
                  🖨️ Print with notes
                </button>
                <button className="ghost-button" onClick={() => {
                  navigator.clipboard.writeText(notes)
                }} disabled={!notes.trim()}>
                  📋 Copy notes
                </button>
              </div>
            </div>
          )}

          {/* Tips tab */}
          {activeTab === 'tips' && (
            <div className="cp-sections">
              <Section icon="💡" title="Preparation Tips" color="#f59e0b">
                {guide?.preparation_tips?.map((tip, i) => (
                  <div key={i} className="cp-tip-item">
                    <span className="cp-tip-num" style={{ background: '#f59e0b' }}>{i + 1}</span>
                    <p style={{ margin: 0, fontSize: '0.9rem', lineHeight: 1.6 }}>{tip}</p>
                  </div>
                ))}
              </Section>

              <Section icon="🧘" title="On the Day of Your Appointment" color="#8b5cf6">
                {[
                  'Arrive 10–15 minutes early to complete any paperwork.',
                  'Bring a trusted friend or family member if you feel anxious.',
                  'Turn your phone to silent but keep it accessible for notes.',
                  'Be honest about your lifestyle — alcohol, smoking, diet, and stress all matter.',
                  'Ask the doctor to explain anything you don\'t understand in plain language.',
                  'Don\'t leave without knowing the next step — a test, referral, or follow-up date.',
                  'Ask for a written summary or prescription if needed.',
                ].map((tip, i) => (
                  <div key={i} className="cp-tip-item">
                    <span className="cp-tip-num" style={{ background: '#8b5cf6' }}>{i + 1}</span>
                    <p style={{ margin: 0, fontSize: '0.9rem', lineHeight: 1.6 }}>{tip}</p>
                  </div>
                ))}
              </Section>

              <Section icon="📱" title="After Your Appointment" color="#2a7c89">
                {[
                  'Write down what the doctor said while it\'s fresh in your memory.',
                  'Fill any prescriptions the same day if possible.',
                  'Book any follow-up tests or referrals before leaving the clinic.',
                  'Log your symptoms in HealthPilot to track your progress.',
                  'Set a reminder for your next appointment or medication.',
                ].map((tip, i) => (
                  <div key={i} className="cp-tip-item">
                    <span className="cp-tip-num" style={{ background: '#2a7c89' }}>{i + 1}</span>
                    <p style={{ margin: 0, fontSize: '0.9rem', lineHeight: 1.6 }}>{tip}</p>
                  </div>
                ))}
              </Section>
            </div>
          )}
        </>
      )}

      {!result && !loading && (
        <div className="glass-card" style={{ padding: 40, textAlign: 'center' }}>
          <p style={{ fontSize: '2.5rem', marginBottom: 12 }}>🩺</p>
          <h3>Ready to prepare for your appointment?</h3>
          <p className="muted">Describe your symptoms above and we'll generate a personalised guide with questions to ask your doctor, what to bring, and how to make the most of your visit.</p>
        </div>
      )}
    </div>
  )
}
